{{ if .Values.logging.enabled -}}
{{- with $.Values.logging.eventTailer }}
{{- if .create }}
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: EventTailer
metadata:
  name: {{ .name }}
spec:
  controlNamespace: {{ $.Values.logging.controlNamespace | default $.Release.Namespace }}
  {{- with .image }}
  image:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .pvc }}
  {{- if .enabled }}
  positionVolume:
    pvc:
      spec:
        accessModes: {{ .accessModes }}
        resources:
          requests:
            storage: {{ .storage }}
        volumeMode: {{ .volumeMode }}
        {{- with .storageClassName }}
        storageClassName: {{ . }}
        {{- end }}
  {{- end }}{{/* end if enabled */}}
  {{- end }}{{/* end with pvc */}}
  {{- with .workloadMetaOverrides }}
  workloadMetaOverrides:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .workloadOverrides }}
  workloadOverrides:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .containerOverrides }}
  containerOverrides:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}{{/* end if create */}}
{{- end }}{{/* end with event-tailer */}}
{{- end }}{{/* end if logging-enabled */}}
